#!/bin/sh

should_fail=0

# remove all git added empty meta files & directory
for directory in $(git status -s | egrep '^A.*.meta$' | awk '{print $2}' | sed 's|.meta$||g' | xargs -n1 -I{} find "{}" -empty 2> /dev/null)
do
	git reset "${directory}.meta"
	rmdir "$directory"
	rm "${directory}.meta"
	should_fail=1
done

# remove all unstaged empty meta files & directory
for directory in $(git status -s | egrep '.meta$' | awk '{print $2}' | sed 's|.meta$||g' | xargs -n1 -I{} find "{}" -empty 2> /dev/null)
do
	rmdir "$directory"
	rm "${directory}.meta"
done

if [ $should_fail -eq 1 ]; then
	echo "ERROR: git added empty Unity meta files & directory removed. please redo the commit"
	exit $should_fail
fi

