#!/bin/bash

if [ "$2" == "" ]; then
    _GIT_EDIT_FILE=$1
    mv ${_GIT_EDIT_FILE} ${_GIT_EDIT_FILE}.tmp

    _GIT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

    echo ":seedling: ${_GIT_BRANCH_NAME} Create something " > ${_GIT_EDIT_FILE}
    cat $HOME/.gitmessage >> ${_GIT_EDIT_FILE}
    cat ${_GIT_EDIT_FILE}.tmp >> ${_GIT_EDIT_FILE}
fi

