[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo  = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo  = 'OmniSharp/omnisharp-vim'
on_ft = ['csharp']

[[plugins]]
repo  = 'OrangeT/vim-csharp'
on_ft = ['csharp']

[[plugins]]
repo  = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo='tpope/vim-surround'
on_i = 1
